### ISSUE TITLE
Drag and Drop on macosX Installer in simple mode is not working

### ISSUE THREAD

**Issue by opcoach** [eclipse-oomph/oomph#111]
Launch the latest installer version (Installer version: 1.35.0 Build 812) on macosX (Sequoia 15.0.1 (24A348)), and select the link to drag on this page https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup&show=true

There is no drop target working, while on windows we can drag and drop in the top title. 

The workaround (to install) is to use the 'copy Link' and then to click, in advanced mode, in the 'Apply configuration from the clipboard' button (only visible if the clipboard contains a link). It works, but this is not really straightforward.

See the video for the drag : 

https://github.com/user-attachments/assets/9746dbe6-6846-4b6b-b031-87107ca8a5b0

**Comment by opcoach** [comment]
See also : https://github.com/eclipse-platform/eclipse.platform.swt/issues/540

I made some tests... the received transfers are compliant with URLTransfer but unfortunately the url transferred is null ... I will compare with windows to check what is happening...

**Comment by merks** [comment]
Yes, someone will need to contribute a fix.  It's almost impossible for me to develop for macos without the hardware and with virtual boxes extremely hard to come by.  And that's compounded by the fact that drag-and-drop is really hard to debug.  I believe the copy and apply instructions will need to suffice until someone contributes...

**Comment by opcoach** [comment]
Yes i will try to fix it … It could be in the macos swt implementation as the drop using an url transfer works well outside of Eclipse … 
I will compare mac and  windows.

**Comment by merks** [comment]
> Yes i will try to fix it … It could be in the macos swt implementation as the drop using an url transfer works well outside of Eclipse …
> I will compare mac and windows.

That would be totally awesome.! It's been along time, but indeed my sense the last time I looked at this was that the lower levels (SWT) were not behaving correctly...

**Comment by opcoach** [comment]
I created a test project on : https://github.com/opcoach/testswtmacosdroptarget

Already some strange behaviors on Mac...

**Comment by opcoach** [comment]
With my sample I can get a drop working well on macOS ... what ever the drag source : from my sample or from a setup installer page on the web... 

But when I drop in the installer, the drop fails. 

![image](https://github.com/user-attachments/assets/3771ede6-f287-4e58-a616-152e059caa7b)

May be the complex OomphDropAdapter using editing domain is too much for just the label at the top of the window...  The OomphDropAdapter is probably interesting for other cases in the tree to update the oomph model but if the Label Drop target at the top is simple expecting an URL Drop, we could may be simplify it .. 

@merks do you think I can setup a new drop adapter only in this area, and keep the OomphDropAdapter for the other cases (I assume there are other cases)... 

![image](https://github.com/user-attachments/assets/f1ffa7dd-2618-4bd7-a4d3-d218647b3239)

could it produce other side effects ?

**Comment by merks** [comment]
I looked at this problem in Linux, and some things work, e.g., dragging a text selection with a URL from a text editor and dragging the URL from the URL bar in firefox.  I'm surprised that works because I see this as the URI that's processed.

```
https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.ui/master/releng/org.eclipse.ui.releng/platformUIConfiguration.setup&show=true
Auto-launch Eclipse Installer
```
Dragging the Drag Link... doesn't work, and here we see the native transfer is yielding a URL with a line break character in it:
```
![image](https://github.com/user-attachments/assets/9c179119-0242-48ac-ac6e-bd47e8c5ed5e)
```
I can "repair" such a thing in Oomph, but it seems to me that the native transfer is wrong or unhelpful, but at least there is data that could be processed.

Dragging the image does not produce a URL transfer at all:

![image](https://github.com/user-attachments/assets/cff278ca-3a12-46d0-b245-d91b940547a1)

Dragging and dropping it onto a text editor opens a new editor with stuff in it that looks like the contents of the page:

![image](https://github.com/user-attachments/assets/fe992ea8-48cc-42c7-977a-6f46c13ee6e7)

When I look at all the native transfers being called in OomphTransferDelegate I don't see any of those return something useful for this case.   So it just doesn't appear that dragging that thing is like dragging a link as far as SWT is concerned.

Probably macos has similar problems. 

The places to look are in org.eclipse.oomph.internal.ui.OomphTransferDelegate where nativeToJava is being called to get the dragged contents out of the native layer.

If you can instrument this code and provide details about what the framework seems coming out of the transfer layer, that would be very helpful to try to get at least some of these working...

![image](https://github.com/user-attachments/assets/2c97549d-7936-4051-87f7-15f88b1177dd)
