### ISSUE TITLE
Download Link broken

### ISSUE THREAD

**Issue by bohni** [eclipse-oomph/oomph#118]
On the webpage https://wiki.eclipse.org/Eclipse_Installer the Download Links for Installers without JRE (eg.- windows: https://www.eclipse.org/downloads/download.php?file=/oomph/products/latest/eclipse-inst-win64.exe) are broken.

I cannot use the Installer with provided JRE, because I need to add a cert to the Java cert store.

https://download.eclipse.org/oomph/products/ lists the exe without `win64` -> `eclipse-inst-.exe`

**Comment by merks** [comment]
Sorry the wiki is read-only now.  You can see all the installers here:

https://download.eclipse.org/justj/?file=oomph/products/latest

Note that I expect that latest installers with a JRE will just work because it now uses the system cacerts:

https://github.com/eclipse-oomph/oomph/commit/e86bb9282e0f3474a8d8b9bb1f046e916eb079ff#diff-8c53f084f87f920eaa61c6ce0865e42ec9a97912e38b0e9070b129afebfda057

**Comment by bohni** [comment]
The name of the exe file is still missing win64 in it, but I will give the JRE version another try.

Thanks

**Comment by bohni** [comment]
https://download.eclipse.org/justj/?file=oomph/epp/2024-12/M3 also misses the correctly named win64 exe

**Comment by merks** [comment]
I see what you mean now. Sorry. I’ll look into it soon.

**Comment by merks** [comment]
Thanks for reporting the problem and for correcting my misunderstanding. 

It’s fixed now

https://download.eclipse.org/justj/?file=oomph/products/latest
