### ISSUE TITLE
Problem with Installer Build 172 Version 1.30.0

### ISSUE THREAD

**Issue by Ramzyromdhan** [eclipse-oomph/oomph#33]
I have first considered [asking a question](https://www.eclipse.org/setups/installer/question?version=1.30.0+Build+172).

 I understand that without details about the problem and how to reproduce then problem, no one can fix a problem for me.  Therefore I have attached log details and screen captures below:
```
Log Details...

"I successfully installed the Java JDK, but I encountered an error during the Eclipse installation. I believe I may have accidentally deleted something on my computer that Eclipse requires for installation. Please help me find a solution."

```
![Screenshot 2023-10-20 221218](https://github.com/eclipse-oomph/oomph/assets/140837646/d414c255-f1b3-45f2-911a-1ea9c498d048)
![Screenshot 2023-10-20 221631](https://github.com/eclipse-oomph/oomph/assets/140837646/c041a07d-0611-4406-815d-f76db9f05407)

**Comment by merks** [comment]
See that the "Show Log" in the overlay is underlined because it is a **link** to the log.  I need the details of that log to know what has gone wrong...

The first thing you might try to do is use the menu 

![image](https://github.com/eclipse-oomph/oomph/assets/208716/f6400dd6-4bdf-4f7a-84ac-b4f683442a41)

to open this dialog:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/39f9aa0f-0493-41b1-a38d-bea8cc0e2e3e)

and analyze the agent to check if there are any damaged artifacts and try to repair them:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/e2a59b4f-dd15-4c6b-b655-750a641bdce0)

Sometimes virus checkers block the copying/moving of files such that they don't properly end up in the pool...

**Comment by merks** [comment]
Feel free to reopen this issue when you are able to provide details about what is failing.
