### ISSUE TITLE
Double download during OOmphing

### ISSUE THREAD

**Issue by jukzi** [eclipse-oomph/oomph#45]
I oomphed https://www.eclipse.org/setups/installer/?url=https://raw.githubusercontent.com/eclipse-platform/eclipse.platform.releng.aggregator/master/oomph/PlatformSDKConfiguration.setup

And just saw that some things are downloaded/fetched twice - at least the progress log says that. Example com.sun.jna:

```
Line 124: Downloading com.sun.jna
Line 718: Downloading com.sun.jna
Line 719: Fetching com.sun.jna_5.13.0.v20230812-1000.jar from https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.29.0/plugins/ (1.81MB)
Line 720: Fetching com.sun.jna_5.13.0.v20230812-1000.jar from https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/release/4.29.0/plugins/
```

i had bundle pool disabled.

also for:
```
org.eclipse.oomph.setup.workingsets
org.eclipse.oomph.setup.workbench
org.eclipse.oomph.setup.targlets
org.eclipse.oomph.setup.projects
org.eclipse.oomph.setup.pde
org.eclipse.oomph.setup.jdt
org.eclipse.jgit.ssh.apache
org.eclipse.emf.databinding
```

**Comment by merks** [comment]
There is really a lot of stuff logged, so much so that we have to filter to reduce the noise:

https://github.com/eclipse-oomph/oomph/blob/master/plugins/org.eclipse.oomph.setup/src/org/eclipse/oomph/setup/log/ProgressLogFilter.java

I wouldn't read too much (any) semantic significance in duplicate log messages in terms of actual duplicate activities.   We do try to avoid duplicates from printing the same line more than once:

https://github.com/eclipse-oomph/oomph/blob/a617d781afc61f0ee7e23c302efa26c41a526a9a/plugins/org.eclipse.oomph.setup/src/org/eclipse/oomph/setup/log/ProgressLogFilter.java#L87C14-L87C35

It's really not worth my very limited resource to track down an issue such as this. Maybe you plan such an activity, but if not, it will never happen...

**Comment by jukzi** [comment]
ok, if its only a logging issue just ignore it
