### ISSUE TITLE
Show location of current Oomph setup

### ISSUE THREAD

**Issue by tivervac** [eclipse-oomph/oomph#85]
![image](https://github.com/eclipse-oomph/oomph/assets/3389524/88c263c6-71dd-4c00-b8cf-7a836ab67974)

At our company, we use different Oomph files. Sometimes, we use the local one in our git repo (in one of our multiple clones), sometimes one that is uploaded to some server, and sometimes a local one to workaround some issues. The current setup (see above) doesn't show you which of these is selected, forcing you to remove the current one and add the one you need to ensure you have the right one.

**Comment by merks** [comment]
Did you know about this control's details?

![image](https://github.com/eclipse-oomph/oomph/assets/208716/51784e2c-47a0-40cf-9372-424ab3f8643f)

You can see the information about the location of a setup is really quite a long string in the normal/standard case where the catalog is loaded via the setups zip.  What specifically are you hoping to see and where are you hoping to see it?  Perhaps the full URI in the hover over the product?

**Comment by merks** [comment]
Keep in mind though that these URLs in generally are REALLY RIDICULOUSLY LONG:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/d2ff761d-4f16-494b-bfa1-5335c74f15f6)

I would not want to see that pushed into everyone's face in general everywhere.

On the project page (where similar location concerns might arise), we do show hover information in general:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/c19f2579-f745-49f3-8286-9f1378bce396)

But for products we show information about the product directly in the info field based on the selection.

Somehow I'd like to do something that's not so constantly in-your-face for everyone when very few would really want that or would want it only occasionally/rarely...

**Comment by merks** [comment]
The hovers have the problem that the long URLs don't display well because the hover box is not very big.  So I added a control to determine whether to show link information or not.

![image](https://github.com/eclipse-oomph/oomph/assets/208716/f0cb5331-e9a1-4959-9412-9d3256f4f54b)

I show link information only if the object is directly contained by a resource, so only the two catalogs show the details.  The tool item's state is persistent.  It's disabled by default.  I show both the direct URI of the resource as sell as the resolved URI, if it is different.

The project page has the same control:

![image](https://github.com/eclipse-oomph/oomph/assets/208716/f91da213-4707-4865-9b16-a3d6622a6eb4)

I've shortened the very long archive: URIs to show only the location of the archive.

**Comment by tivervac** [comment]
Thanks for the very quick fix @merks Testing it out, it does exactly what I need it to do. It's now very clear which URI is used. I do see now what you mean by long URIs though.

![image](https://github.com/eclipse-oomph/oomph/assets/3389524/1d369a46-4b84-4c41-b3bc-1d4b1a1efdde)

**Comment by merks** [comment]
I should add some special logic for user-ext scheme to show less detail. I think only the resolved location is of interest…. What do you think?

**Comment by tivervac** [comment]
Yes that seems like a good addition
